# General rules
[[redirects]]
  from = "https://villoro.netlify.com/*"
  to = "https://villoro.com/:splat"
  status = 301

[[redirects]]
  from = "https://villoro.com/home"
  to = "https://villoro.com"
  status = 301


# Old posts
[[redirects]]
  from = "/post/personal_web"
  to = "/blog/personal-webpage"
  status = 301

[[redirects]]
  from = "/post/black"
  to = "/blog/black-code-formatting"
  status = 301

[[redirects]]
  from = "/post/sql_alchemy"
  to = "/blog/sql-alchemy-python"
  status = 301

[[redirects]]
  from = "/post/colors"
  to = "/blog/material-colors-and-palettes"
  status = 301

[[redirects]]
  from = "/post/strings_python"
  to = "/blog/string-best-practices-with-python"
  status = 301

[[redirects]]
  from = "/post/singleton"
  to = "/blog/singleton-python"
  status = 301

[[redirects]]
  from = "/post/blog_basic_tools"
  to = "/blog/basic-tools-for-blogs"
  status = 301

[[redirects]]
  from = "/post/static_webpage"
  to = "/blog/create-static-website"
  status = 301

[[redirects]]
  from = "/post/aws_ec2"
  to = "/blog/creating-ec2-aws"
  status = 301

[[redirects]]
  from = "/post/airflow"
  to = "/blog/setting-up-airflow"
  status = 301

[[redirects]]
  from = "/post/nginx_gunicorn"
  to = "/blog/serving-python-app-nginx-gunicorn"
  status = 301

[[redirects]]
  from = "/post/tables_format"
  to = "/blog/storing-tables-efficiently-pandas"
  status = 301

[[redirects]]
  from = "/post/intro_machine_learning"
  to = "/blog/intro-machine-learning"
  status = 301

[[redirects]]
  from = "/post/decorators"
  to = "/blog/python-decorators"
  status = 301

[[redirects]]
  from = "/post/aws_lambda"
  to = "/blog/aws-lambdas-to-control-ec2"
  status = 301

[[redirects]]
  from = "/post/pypi"
  to = "/blog/creating-python-packages"
  status = 301

[[redirects]]
  from = "/post/passwords_encryption"
  to = "/blog/encrypting-secrets-python"
  status = 301

[[redirects]]
  from = "/post/logging"
  to = "/blog/python-logging"
  status = 301

[[redirects]]
  from = "/post/numba"
  to = "/blog/improve-python-performance-with-numba"
  status = 301

[[redirects]]
  from = "/post/gitflow"
  to = "/blog/using-gitflow"
  status = 301

[[redirects]]
  from = "/post/git_ssh"
  to = "/blog/git-with-ssh"
  status = 301

[[redirects]]
  from = "/post/google_analytics_etl"
  to = "/blog/google-analytics-etl-python"
  status = 301

[[redirects]]
  from = "/post/dropbox_python"
  to = "/blog/dropbox-python"
  status = 301

[[redirects]]
  from = "/post/pandas_intro"
  to = "/blog/pandas-intro"
  status = 301

[[redirects]]
  from = "/post/pyspark_intro"
  to = "/blog/pyspark-intro"
  status = 301

[[redirects]]
  from = "/post/h2o_automl"
  to = "/blog/h2o-automl"
  status = 301

[[redirects]]
  from = "/post/databricks"
  to = "/blog/databricks-intro"
  status = 301

[[redirects]]
  from = "/post/pyspark_example"
  to = "/blog/pyspark-example"
  status = 301

[[redirects]]
  from = "/post/luigi"
  to = "/blog/luigi-orchestrator"
  status = 301

[[redirects]]
  from = "/post/cmder"
  to = "/blog/cmder-terminal-windows"
  status = 301

[[redirects]]
  from = "/post/poetry"
  to = "/blog/poetry-python-package-manager"
  status = 301

[[redirects]]
  from = "/post/pre_commit"
  to = "/blog/pre-commit"
  status = 301

[[redirects]]
  from = "/post/python_environment_config"
  to = "/blog/python-environmint-configuration"
  status = 301

[[redirects]]
  from = "/post/pyspark_java_udf"
  to = "/blog/java-udf-pyspark"
  status = 301

[[redirects]]
  from = "/post/ing_api"
  to = "/blog/ing-api-python"
  status = 301

[[redirects]]
  from = "/post/regex"
  to = "/blog/regex-python"
  status = 301

[[redirects]]
  from = "/post/reading_from_redshift"
  to = "/blog/reading-from-redshift-with-pyarrow"
  status = 301
