name: Version

on:
  pull_request:

jobs:
  check_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            code:
              - 'src/**'
              - 'public/**'
              - 'package.json'

      - name: Set up python
        if: steps.changes.outputs.code == 'true'
        uses: actions/setup-python@v4

      - name: Install requirements
        if: steps.changes.outputs.code == 'true'
        run: pip install poetry==1.6.1 poetry-bumpversion==0.3.1 loguru click

      # Get version from main
      - name: Checkout main
        if: steps.changes.outputs.code == 'true'
        uses: actions/checkout@v3
        with:
          # Those are needed because of https://github.com/EndBug/add-and-commit#working-with-prs
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: main
      - name: Get main version
        if: steps.changes.outputs.code == 'true'
        run: python .github/scripts/get_version.py --name=main

      # Get version from current branch
      - name: Checkout current branch
        if: steps.changes.outputs.code == 'true'
        uses: actions/checkout@v3
        with:
          # Those are needed because of https://github.com/EndBug/add-and-commit#working-with-prs
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Get current version
        if: steps.changes.outputs.code == 'true'
        run: python .github/scripts/get_version.py --name=current

      # Checks if version needs updating
      - name: Check if version needs to be updated
        if: steps.changes.outputs.code == 'true'
        run: python .github/scripts/check_if_update_needed.py --version_current=$VERSION_CURRENT --version_main=$VERSION_MAIN
