name: Tag Version

on:
  push:
    branches:
      - main
    paths:
      - package.json

permissions:
  contents: write

jobs:
  tag_version:
    runs-on: ubuntu-latest
    steps:
      - uses: villoro/vhooks/tag_version@1.2.0
        with:
          file: package.json
          path: version
